### ISSUE TITLE
Decide research question

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/rds-course#15]

**Comment by callummole** [comment]
## RQ Proposal
_and some initial thoughts of how it will work across modules_
(adapted from Greg's 13/07/21 notes - #16 )

We discussed having a broad research question that develops across the modules. 

Initial research qu is related to Aldabe et al., 2010, but is broad, such as **Which variables predict self-reported-health**?

We could also make it poorly specified, such as **What factors affect health**? Since the project scoping process in M1 could make it more realistic wrt our dataset. 

The job of M3 & M4 is to tackle the qu. M4 in particular breaks the RQ down in manageable chunks for developing models.
- Stages to answer it: 
      - Exploratory visuals to get familiar with the dataset. This will be done in M3, with the chosen examples neatly foreshadowing the relationships we examine in M4.
      -  As researchers, we break down the qu into a simplified series of questions, for example:
            - how are we measuring health? What is the outcome measure for our model?
            - by what method are we predicting health? (e.g. logistic regression).
      - A predictive model is built to understand if an initial set of variables can predict the outcome. This is a typical but imperfect way to understand if there are associations
        - More variables are added and/or a different model is used. 
        - The model predicts in one country but maybe fails in others so we discuss methods to address that (possibly multilevel modeling). 
        - A good predictive model does not necessarily answer the question of which variables are associated. We then discuss other steps to improve our answer.
        - We don't pretend to answer the question since we don't have time for it. Rather the last part of M4 will be discussing future directions and point the students in the direction of how they could build upon what we have done.

**Comment by gmingas** [comment]
TRIPOD framework which might be helpful to give to attendees when answering the research question. Could also be used in some parts of taught session.
https://bmjopen.bmj.com/content/11/7/e048008

**Comment by callummole** [comment]
[Paper based on RQ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3678208/)

**Comment by fedenanni** [comment]
This is the final specific RQ, MVP and task that @crangelsmith and I have defined this morning. Feel free to edit / improve it:

**RQ:** We want to investigate the contribution of material, occupational, and psychosocial factors on the self reported health (SRH) across different European countries. We will use SRH information collected by the Wave 2 and 3 of the EQLTS survey, aware that they offer only a partial representation of European populations and that SRH is per-se a highly subjective indicator, difficult to compare across countries.

**MVP:** limit the study to UK and to Wave 3 initially

**Task:**  binarise SHR the following way: [“”Very good”, “Good” and “Fair”] as good and [“”Bad”, “Very Bad”] as bad. Use columns ... to predict SHR.
