### ISSUE TITLE
Module 2 Development (Teaching Material)

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/rds-course#8]
-  Module plan: https://hackmd.io/2jO67RhQSGysNetJ-ReJ7Q
- "Getting Data" lesson: https://hackmd.io/7rron7vtTLK_uKx_5A_PrQ

**Comment by gmingas** [comment]
Note on EDI elements in this lesson: It would be great if we could mention the issue of *missing data* and activism that aims to challenge this problem, i.e. counter data.
- There are many datasets that one would expect they would exist but they don't (see [here](https://github.com/MimiOnuoha/missing-datasets)). This might happen due to political or cultural reasons and often expresses biases, systematic failures, oppression.
- Counter data examples include Data for Black Lives ([here](https://d4bl.org/)), [Femicides in Mexico](https://www.opendemocracy.net/en/5050/how-one-woman-is-mapping-femicides-in-mexico/), [NYT COVID case count](https://www.nytimes.com/interactive/2021/us/covid-cases.html), many other mentioned in Data Feminism

Additionally, many of the datasets that organisations/states publish might be missing important variables, not break down numbers by gender, age, race etc (which can hide many biases) and/or exclude people that should be there (e.g. children's mental health is often not measured, data used for designing products or conducting medical research have historically been male-dominated).
