### ISSUE TITLE
Error in coursebook build (can't find file)

### ISSUE THREAD

**Issue by ots22** [alan-turing-institute/rds-course#90]
Result of third cell in [this section](https://alan-turing-institute.github.io/rds-course/modules/m3/3.5-DataVisForExploration.html#reading-the-data) has
```
...
No such file or directory: './data/UKDA-7724-csv/csv/eqls_2011.csv'
```

**Comment by lannelin** [comment]
@callummole @crangelsmith 
Doesn't seem to affect the rest of the cells on this page. Might just be good to be aware of, for now, so you're not surprised when teaching.

Long term fix could be: 

- re-host the data in the repository; **or**
- include a download in the build

**Comment by callummole** [comment]
This has been fixed in [this commit](https://github.com/alan-turing-institute/rds-course/commit/ff7023c163fc86b4746aad811211956d8763d301) by adding `exclude_patterns` to the `execute` field in the config file

We now do not execute the notebooks that rely on the data file, and instead build with the saved output. This requires that you have ran these locally before building the notebook.
